#!/bin/bash

LLM_ROUTER_TIMEOUT=500 \
  LLM_ROUTER_IN_DEBUG=1 \
  LLM_ROUTER_MINIMUM=1 \
  LLM_ROUTER_PROMPTS_DIR="resources/prompts" \
  LLM_ROUTER_MODELS_CONFIG="resources/configs/models-config.json" \
  LLM_ROUTER_LOG_FILENAME="llm-proxy-rest.log" \
  LLM_ROUTER_EP_PREFIX="/api" \
  LLM_ROUTER_DEFAULT_EP_LANGUAGE="pl" \
  LLM_ROUTER_SERVER_TYPE=gunicorn \
  LLM_ROUTER_SERVER_PORT=8080 \
  LLM_ROUTER_SERVER_HOST="0.0.0.0" \
  LLM_ROUTER_SERVER_WORKERS_COUNT=4 \
  LLM_ROUTER_EXTERNAL_TIMEOUT=300 \
  LLM_ROUTER_USE_PROMETHEUS=1 \
  python3 -m llm_router_api.rest_api
