name: Build (Docker + PyPI)

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  lint:
    uses: ./.github/workflows/lint.yml

  docker:
    needs: [tests, lint]
    uses: ./.github/workflows/docker.yml

  pypi:
    needs: [tests, lint]
    uses: ./.github/workflows/pypi.yml
