name: Build (Docker + PyPI)

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tests:
    uses: ./.github/workflows/build/tests.yml

  docker:
    needs: tests
    uses: ./.github/workflows/build/docker.yml
    with:
      run-tests: false

  pypi:
    needs: tests
    uses: ./.github/workflows/build/pypi.yml
    with:
      run-tests: false
